package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/iotaledger/hive.go/app"
	"github.com/iotaledger/hive.go/apputils/config"
	lockboxApp "github.com/iotaledger/lockbox/v2/components/app"
)

func createMarkdownFile(app *app.App, markdownHeaderPath string, markdownFilePath string, ignoreFlags map[string]struct{}, replaceTopicNames map[string]string) {

	markdownHeader := ""

	if markdownHeaderPath != "" {
		// read markdown header from file
		markdownHeaderFile, err := os.ReadFile(markdownHeaderPath)
		if err != nil {
			panic(err)
		}
		markdownHeader = string(markdownHeaderFile)
	}

	// add notice about auto-generation
	if strings.HasPrefix(markdownHeader, "---") {
		// Header has meta tags, add the notice after it
		markdownHeader = strings.Replace(markdownHeader, "---", `---
# !!!DO NOT MODIFY!!!
# This file is auto-generated by the gendoc tool based on the source code of the app.`, 1)
	} else {
		markdownHeader = `# !!!DO NOT MODIFY!!!
# This file is auto-generated by the gendoc tool based on the source code of the app.
` + markdownHeader
	}

	println(fmt.Sprintf("Create markdown file for %s...", app.Info().Name))

	md := config.GetConfigurationMarkdown(app.Config(), app.FlagSet(), ignoreFlags, replaceTopicNames)
	if err := os.WriteFile(markdownFilePath, append([]byte(markdownHeader), []byte(md)...), os.ModePerm); err != nil {
		panic(err)
	}

	println(fmt.Sprintf("Markdown file for %s stored: %s", app.Info().Name, markdownFilePath))
}

func createDefaultConfigFile(app *app.App, configFilePath string, ignoreFlags map[string]struct{}) {

	println(fmt.Sprintf("Create default configuration file for %s...", app.Info().Name))

	conf := config.GetDefaultAppConfigJSON(app.Config(), app.FlagSet(), ignoreFlags)
	if err := os.WriteFile(configFilePath, []byte(conf), os.ModePerm); err != nil {
		panic(err)
	}

	println(fmt.Sprintf("Default configuration file for %s stored: %s", app.Info().Name, configFilePath))
}

func main() {
	// flags to ignore
	ignoreFlags := make(map[string]struct{})
	ignoreFlags["db.debug"] = struct{}{}
	ignoreFlags["p2p.autopeering.inboundPeers"] = struct{}{}
	ignoreFlags["p2p.autopeering.outboundPeers"] = struct{}{}
	ignoreFlags["p2p.autopeering.saltLifetime"] = struct{}{}

	replaceTopicNames := make(map[string]string)
	replaceTopicNames["app"] = "Application"
	replaceTopicNames["p2p"] = "Peer to Peer"
	replaceTopicNames["db"] = "Database"
	replaceTopicNames["pow"] = "Proof of Work"
	replaceTopicNames["jwtAuth"] = "JWT Auth"
	replaceTopicNames["warpsync"] = "WarpSync"
	replaceTopicNames["api"] = "API"
	replaceTopicNames["tipsel"] = "Tipselection"
	replaceTopicNames["inx"] = "INX"
	replaceTopicNames["lockbox"] = "LockBox"

	// create the app with config
	application := lockboxApp.App()

	// generate markdown file
	createMarkdownFile(
		application,
		"configuration_header.md",
		"../../configuration.md",
		ignoreFlags,
		replaceTopicNames,
	)

	// generate default config
	createDefaultConfigFile(
		application,
		"../../config_defaults.json",
		ignoreFlags,
	)
}