// Code generated by protoc-gen-go. DO NOT EDIT.
// Stub implementation for compilation - generate from lockbox.proto using:
// protoc --go_out=. --go-grpc_out=. lockbox.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// LockBoxServiceServer is the server API for LockBoxService service.
type LockBoxServiceServer interface {
	LockAsset(context.Context, *LockAssetRequest) (*LockAssetResponse, error)
	UnlockAsset(context.Context, *UnlockAssetRequest) (*UnlockAssetResponse, error)
	GetAssetStatus(context.Context, *GetAssetStatusRequest) (*GetAssetStatusResponse, error)
	ListAssets(*ListAssetsRequest, LockBoxService_ListAssetsServer) error
	CreateMultiSig(context.Context, *CreateMultiSigRequest) (*CreateMultiSigResponse, error)
	EmergencyUnlock(context.Context, *EmergencyUnlockRequest) (*EmergencyUnlockResponse, error)
	GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error)
}

// UnimplementedLockBoxServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLockBoxServiceServer struct{}

func (UnimplementedLockBoxServiceServer) LockAsset(context.Context, *LockAssetRequest) (*LockAssetResponse, error) {
	return nil, nil
}
func (UnimplementedLockBoxServiceServer) UnlockAsset(context.Context, *UnlockAssetRequest) (*UnlockAssetResponse, error) {
	return nil, nil
}
func (UnimplementedLockBoxServiceServer) GetAssetStatus(context.Context, *GetAssetStatusRequest) (*GetAssetStatusResponse, error) {
	return nil, nil
}
func (UnimplementedLockBoxServiceServer) ListAssets(*ListAssetsRequest, LockBoxService_ListAssetsServer) error {
	return nil
}
func (UnimplementedLockBoxServiceServer) CreateMultiSig(context.Context, *CreateMultiSigRequest) (*CreateMultiSigResponse, error) {
	return nil, nil
}
func (UnimplementedLockBoxServiceServer) EmergencyUnlock(context.Context, *EmergencyUnlockRequest) (*EmergencyUnlockResponse, error) {
	return nil, nil
}
func (UnimplementedLockBoxServiceServer) GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error) {
	return nil, nil
}

// LockBoxService_ListAssetsServer is the server stream for ListAssets
type LockBoxService_ListAssetsServer interface {
	Send(*ListAssetsResponse) error
	grpc.ServerStream
}

// RegisterLockBoxServiceServer registers the server
func RegisterLockBoxServiceServer(s *grpc.Server, srv LockBoxServiceServer) {
	// Stub registration
}

// Message types

type LockAssetRequest struct {
	OwnerAddress      string
	OutputId          []byte
	LockDurationSeconds int64
	LockScript        string
	MultiSigAddresses []string
	MinSignatures     int32
}

type LockAssetResponse struct {
	AssetId    string
	LockTime   int64
	UnlockTime int64
	Status     string
}

type UnlockAssetRequest struct {
	AssetId      string
	Signatures   [][]byte
	UnlockParams map[string]string
}

type UnlockAssetResponse struct {
	AssetId    string
	OutputId   []byte
	UnlockTime int64
	Status     string
}

type GetAssetStatusRequest struct {
	AssetId string
}

type GetAssetStatusResponse struct {
	AssetId      string
	Status       string
	LockTime     int64
	UnlockTime   int64
	OwnerAddress string
	Amount       uint64
}

type ListAssetsRequest struct {
	OwnerAddress string
	Status       string
	PageSize     int32
	PageToken    string
}

type ListAssetsResponse struct {
	Assets        []*AssetInfo
	NextPageToken string
}

type AssetInfo struct {
	AssetId    string
	Status     string
	LockTime   int64
	UnlockTime int64
	Amount     uint64
}

type CreateMultiSigRequest struct {
	Addresses     []string
	MinSignatures int32
}

type CreateMultiSigResponse struct {
	MultiSigId string
	Address    string
}

type EmergencyUnlockRequest struct {
	AssetId             string
	Reason              string
	EmergencySignatures [][]byte
}

type EmergencyUnlockResponse struct {
	AssetId    string
	Status     string
	UnlockTime int64
}

type GetServiceInfoRequest struct{}

type GetServiceInfoResponse struct {
	Version       string
	Tier          string
	MaxLockTime   int64
	Features      *ServiceFeatures
	NodeLocations []string
}

type ServiceFeatures struct {
	MultiSigSupport      bool
	EmergencyUnlock      bool
	GeographicRedundancy int32
	ScriptingEnabled     bool
}
