// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: lockbox.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LockBoxService_LockAsset_FullMethodName       = "/lockbox.LockBoxService/LockAsset"
	LockBoxService_UnlockAsset_FullMethodName     = "/lockbox.LockBoxService/UnlockAsset"
	LockBoxService_GetAssetStatus_FullMethodName  = "/lockbox.LockBoxService/GetAssetStatus"
	LockBoxService_ListAssets_FullMethodName      = "/lockbox.LockBoxService/ListAssets"
	LockBoxService_CreateMultiSig_FullMethodName  = "/lockbox.LockBoxService/CreateMultiSig"
	LockBoxService_EmergencyUnlock_FullMethodName = "/lockbox.LockBoxService/EmergencyUnlock"
	LockBoxService_GetServiceInfo_FullMethodName  = "/lockbox.LockBoxService/GetServiceInfo"
)

// LockBoxServiceClient is the client API for LockBoxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LockBoxServiceClient interface {
	LockAsset(ctx context.Context, in *LockAssetRequest, opts ...grpc.CallOption) (*LockAssetResponse, error)
	UnlockAsset(ctx context.Context, in *UnlockAssetRequest, opts ...grpc.CallOption) (*UnlockAssetResponse, error)
	GetAssetStatus(ctx context.Context, in *GetAssetStatusRequest, opts ...grpc.CallOption) (*GetAssetStatusResponse, error)
	ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListAssetsResponse], error)
	CreateMultiSig(ctx context.Context, in *CreateMultiSigRequest, opts ...grpc.CallOption) (*CreateMultiSigResponse, error)
	EmergencyUnlock(ctx context.Context, in *EmergencyUnlockRequest, opts ...grpc.CallOption) (*EmergencyUnlockResponse, error)
	GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error)
}

type lockBoxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLockBoxServiceClient(cc grpc.ClientConnInterface) LockBoxServiceClient {
	return &lockBoxServiceClient{cc}
}

func (c *lockBoxServiceClient) LockAsset(ctx context.Context, in *LockAssetRequest, opts ...grpc.CallOption) (*LockAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockAssetResponse)
	err := c.cc.Invoke(ctx, LockBoxService_LockAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxServiceClient) UnlockAsset(ctx context.Context, in *UnlockAssetRequest, opts ...grpc.CallOption) (*UnlockAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockAssetResponse)
	err := c.cc.Invoke(ctx, LockBoxService_UnlockAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxServiceClient) GetAssetStatus(ctx context.Context, in *GetAssetStatusRequest, opts ...grpc.CallOption) (*GetAssetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetStatusResponse)
	err := c.cc.Invoke(ctx, LockBoxService_GetAssetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxServiceClient) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListAssetsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LockBoxService_ServiceDesc.Streams[0], LockBoxService_ListAssets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListAssetsRequest, ListAssetsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LockBoxService_ListAssetsClient = grpc.ServerStreamingClient[ListAssetsResponse]

func (c *lockBoxServiceClient) CreateMultiSig(ctx context.Context, in *CreateMultiSigRequest, opts ...grpc.CallOption) (*CreateMultiSigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMultiSigResponse)
	err := c.cc.Invoke(ctx, LockBoxService_CreateMultiSig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxServiceClient) EmergencyUnlock(ctx context.Context, in *EmergencyUnlockRequest, opts ...grpc.CallOption) (*EmergencyUnlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmergencyUnlockResponse)
	err := c.cc.Invoke(ctx, LockBoxService_EmergencyUnlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxServiceClient) GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceInfoResponse)
	err := c.cc.Invoke(ctx, LockBoxService_GetServiceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockBoxServiceServer is the server API for LockBoxService service.
// All implementations must embed UnimplementedLockBoxServiceServer
// for forward compatibility.
type LockBoxServiceServer interface {
	LockAsset(context.Context, *LockAssetRequest) (*LockAssetResponse, error)
	UnlockAsset(context.Context, *UnlockAssetRequest) (*UnlockAssetResponse, error)
	GetAssetStatus(context.Context, *GetAssetStatusRequest) (*GetAssetStatusResponse, error)
	ListAssets(*ListAssetsRequest, grpc.ServerStreamingServer[ListAssetsResponse]) error
	CreateMultiSig(context.Context, *CreateMultiSigRequest) (*CreateMultiSigResponse, error)
	EmergencyUnlock(context.Context, *EmergencyUnlockRequest) (*EmergencyUnlockResponse, error)
	GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error)
	mustEmbedUnimplementedLockBoxServiceServer()
}

// UnimplementedLockBoxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLockBoxServiceServer struct{}

func (UnimplementedLockBoxServiceServer) LockAsset(context.Context, *LockAssetRequest) (*LockAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockAsset not implemented")
}
func (UnimplementedLockBoxServiceServer) UnlockAsset(context.Context, *UnlockAssetRequest) (*UnlockAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockAsset not implemented")
}
func (UnimplementedLockBoxServiceServer) GetAssetStatus(context.Context, *GetAssetStatusRequest) (*GetAssetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssetStatus not implemented")
}
func (UnimplementedLockBoxServiceServer) ListAssets(*ListAssetsRequest, grpc.ServerStreamingServer[ListAssetsResponse]) error {
	return status.Error(codes.Unimplemented, "method ListAssets not implemented")
}
func (UnimplementedLockBoxServiceServer) CreateMultiSig(context.Context, *CreateMultiSigRequest) (*CreateMultiSigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMultiSig not implemented")
}
func (UnimplementedLockBoxServiceServer) EmergencyUnlock(context.Context, *EmergencyUnlockRequest) (*EmergencyUnlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmergencyUnlock not implemented")
}
func (UnimplementedLockBoxServiceServer) GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceInfo not implemented")
}
func (UnimplementedLockBoxServiceServer) mustEmbedUnimplementedLockBoxServiceServer() {}
func (UnimplementedLockBoxServiceServer) testEmbeddedByValue()                        {}

// UnsafeLockBoxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LockBoxServiceServer will
// result in compilation errors.
type UnsafeLockBoxServiceServer interface {
	mustEmbedUnimplementedLockBoxServiceServer()
}

func RegisterLockBoxServiceServer(s grpc.ServiceRegistrar, srv LockBoxServiceServer) {
	// If the following call panics, it indicates UnimplementedLockBoxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LockBoxService_ServiceDesc, srv)
}

func _LockBoxService_LockAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxServiceServer).LockAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxService_LockAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxServiceServer).LockAsset(ctx, req.(*LockAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxService_UnlockAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxServiceServer).UnlockAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxService_UnlockAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxServiceServer).UnlockAsset(ctx, req.(*UnlockAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxService_GetAssetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxServiceServer).GetAssetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxService_GetAssetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxServiceServer).GetAssetStatus(ctx, req.(*GetAssetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxService_ListAssets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListAssetsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LockBoxServiceServer).ListAssets(m, &grpc.GenericServerStream[ListAssetsRequest, ListAssetsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LockBoxService_ListAssetsServer = grpc.ServerStreamingServer[ListAssetsResponse]

func _LockBoxService_CreateMultiSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMultiSigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxServiceServer).CreateMultiSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxService_CreateMultiSig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxServiceServer).CreateMultiSig(ctx, req.(*CreateMultiSigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxService_EmergencyUnlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergencyUnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxServiceServer).EmergencyUnlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxService_EmergencyUnlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxServiceServer).EmergencyUnlock(ctx, req.(*EmergencyUnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxService_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxServiceServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxService_GetServiceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxServiceServer).GetServiceInfo(ctx, req.(*GetServiceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LockBoxService_ServiceDesc is the grpc.ServiceDesc for LockBoxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LockBoxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lockbox.LockBoxService",
	HandlerType: (*LockBoxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockAsset",
			Handler:    _LockBoxService_LockAsset_Handler,
		},
		{
			MethodName: "UnlockAsset",
			Handler:    _LockBoxService_UnlockAsset_Handler,
		},
		{
			MethodName: "GetAssetStatus",
			Handler:    _LockBoxService_GetAssetStatus_Handler,
		},
		{
			MethodName: "CreateMultiSig",
			Handler:    _LockBoxService_CreateMultiSig_Handler,
		},
		{
			MethodName: "EmergencyUnlock",
			Handler:    _LockBoxService_EmergencyUnlock_Handler,
		},
		{
			MethodName: "GetServiceInfo",
			Handler:    _LockBoxService_GetServiceInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAssets",
			Handler:       _LockBoxService_ListAssets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lockbox.proto",
}
