// Code generated by protoc-gen-go. DO NOT EDIT.
// Placeholder for protobuf generated code

package proto

// TODO: Generate this file from lockbox.proto using:
// protoc --go_out=. --go-grpc_out=. lockbox.proto

