// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: lockbox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockAssetRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress        string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	OutputId            []byte                 `protobuf:"bytes,2,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	LockDurationSeconds int64                  `protobuf:"varint,3,opt,name=lock_duration_seconds,json=lockDurationSeconds,proto3" json:"lock_duration_seconds,omitempty"`
	LockScript          string                 `protobuf:"bytes,4,opt,name=lock_script,json=lockScript,proto3" json:"lock_script,omitempty"`
	MultiSigAddresses   []string               `protobuf:"bytes,5,rep,name=multi_sig_addresses,json=multiSigAddresses,proto3" json:"multi_sig_addresses,omitempty"`
	MinSignatures       int32                  `protobuf:"varint,6,opt,name=min_signatures,json=minSignatures,proto3" json:"min_signatures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LockAssetRequest) Reset() {
	*x = LockAssetRequest{}
	mi := &file_lockbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAssetRequest) ProtoMessage() {}

func (x *LockAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAssetRequest.ProtoReflect.Descriptor instead.
func (*LockAssetRequest) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{0}
}

func (x *LockAssetRequest) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *LockAssetRequest) GetOutputId() []byte {
	if x != nil {
		return x.OutputId
	}
	return nil
}

func (x *LockAssetRequest) GetLockDurationSeconds() int64 {
	if x != nil {
		return x.LockDurationSeconds
	}
	return 0
}

func (x *LockAssetRequest) GetLockScript() string {
	if x != nil {
		return x.LockScript
	}
	return ""
}

func (x *LockAssetRequest) GetMultiSigAddresses() []string {
	if x != nil {
		return x.MultiSigAddresses
	}
	return nil
}

func (x *LockAssetRequest) GetMinSignatures() int32 {
	if x != nil {
		return x.MinSignatures
	}
	return 0
}

type LockAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	LockTime      int64                  `protobuf:"varint,2,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	UnlockTime    int64                  `protobuf:"varint,3,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockAssetResponse) Reset() {
	*x = LockAssetResponse{}
	mi := &file_lockbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAssetResponse) ProtoMessage() {}

func (x *LockAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAssetResponse.ProtoReflect.Descriptor instead.
func (*LockAssetResponse) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{1}
}

func (x *LockAssetResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *LockAssetResponse) GetLockTime() int64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *LockAssetResponse) GetUnlockTime() int64 {
	if x != nil {
		return x.UnlockTime
	}
	return 0
}

func (x *LockAssetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UnlockAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Signatures    [][]byte               `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	UnlockParams  map[string]string      `protobuf:"bytes,3,rep,name=unlock_params,json=unlockParams,proto3" json:"unlock_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockAssetRequest) Reset() {
	*x = UnlockAssetRequest{}
	mi := &file_lockbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockAssetRequest) ProtoMessage() {}

func (x *UnlockAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockAssetRequest.ProtoReflect.Descriptor instead.
func (*UnlockAssetRequest) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{2}
}

func (x *UnlockAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *UnlockAssetRequest) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *UnlockAssetRequest) GetUnlockParams() map[string]string {
	if x != nil {
		return x.UnlockParams
	}
	return nil
}

type UnlockAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OutputId      []byte                 `protobuf:"bytes,2,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	UnlockTime    int64                  `protobuf:"varint,3,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockAssetResponse) Reset() {
	*x = UnlockAssetResponse{}
	mi := &file_lockbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockAssetResponse) ProtoMessage() {}

func (x *UnlockAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockAssetResponse.ProtoReflect.Descriptor instead.
func (*UnlockAssetResponse) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{3}
}

func (x *UnlockAssetResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *UnlockAssetResponse) GetOutputId() []byte {
	if x != nil {
		return x.OutputId
	}
	return nil
}

func (x *UnlockAssetResponse) GetUnlockTime() int64 {
	if x != nil {
		return x.UnlockTime
	}
	return 0
}

func (x *UnlockAssetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAssetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetStatusRequest) Reset() {
	*x = GetAssetStatusRequest{}
	mi := &file_lockbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetStatusRequest) ProtoMessage() {}

func (x *GetAssetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAssetStatusRequest) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetAssetStatusRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type GetAssetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LockTime      int64                  `protobuf:"varint,3,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	UnlockTime    int64                  `protobuf:"varint,4,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	OwnerAddress  string                 `protobuf:"bytes,5,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Amount        uint64                 `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetStatusResponse) Reset() {
	*x = GetAssetStatusResponse{}
	mi := &file_lockbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetStatusResponse) ProtoMessage() {}

func (x *GetAssetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAssetStatusResponse) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssetStatusResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *GetAssetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAssetStatusResponse) GetLockTime() int64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *GetAssetStatusResponse) GetUnlockTime() int64 {
	if x != nil {
		return x.UnlockTime
	}
	return 0
}

func (x *GetAssetStatusResponse) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *GetAssetStatusResponse) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_lockbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{6}
}

func (x *ListAssetsRequest) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *ListAssetsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAssetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAssetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*AssetInfo           `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_lockbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{7}
}

func (x *ListAssetsResponse) GetAssets() []*AssetInfo {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListAssetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type AssetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LockTime      int64                  `protobuf:"varint,3,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	UnlockTime    int64                  `protobuf:"varint,4,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	Amount        uint64                 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetInfo) Reset() {
	*x = AssetInfo{}
	mi := &file_lockbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetInfo) ProtoMessage() {}

func (x *AssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetInfo.ProtoReflect.Descriptor instead.
func (*AssetInfo) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{8}
}

func (x *AssetInfo) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssetInfo) GetLockTime() int64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *AssetInfo) GetUnlockTime() int64 {
	if x != nil {
		return x.UnlockTime
	}
	return 0
}

func (x *AssetInfo) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateMultiSigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	MinSignatures int32                  `protobuf:"varint,2,opt,name=min_signatures,json=minSignatures,proto3" json:"min_signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMultiSigRequest) Reset() {
	*x = CreateMultiSigRequest{}
	mi := &file_lockbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMultiSigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMultiSigRequest) ProtoMessage() {}

func (x *CreateMultiSigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMultiSigRequest.ProtoReflect.Descriptor instead.
func (*CreateMultiSigRequest) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{9}
}

func (x *CreateMultiSigRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *CreateMultiSigRequest) GetMinSignatures() int32 {
	if x != nil {
		return x.MinSignatures
	}
	return 0
}

type CreateMultiSigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MultiSigId    string                 `protobuf:"bytes,1,opt,name=multi_sig_id,json=multiSigId,proto3" json:"multi_sig_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMultiSigResponse) Reset() {
	*x = CreateMultiSigResponse{}
	mi := &file_lockbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMultiSigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMultiSigResponse) ProtoMessage() {}

func (x *CreateMultiSigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMultiSigResponse.ProtoReflect.Descriptor instead.
func (*CreateMultiSigResponse) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{10}
}

func (x *CreateMultiSigResponse) GetMultiSigId() string {
	if x != nil {
		return x.MultiSigId
	}
	return ""
}

func (x *CreateMultiSigResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EmergencyUnlockRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AssetId             string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Reason              string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	EmergencySignatures [][]byte               `protobuf:"bytes,3,rep,name=emergency_signatures,json=emergencySignatures,proto3" json:"emergency_signatures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EmergencyUnlockRequest) Reset() {
	*x = EmergencyUnlockRequest{}
	mi := &file_lockbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyUnlockRequest) ProtoMessage() {}

func (x *EmergencyUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyUnlockRequest.ProtoReflect.Descriptor instead.
func (*EmergencyUnlockRequest) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{11}
}

func (x *EmergencyUnlockRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *EmergencyUnlockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EmergencyUnlockRequest) GetEmergencySignatures() [][]byte {
	if x != nil {
		return x.EmergencySignatures
	}
	return nil
}

type EmergencyUnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UnlockTime    int64                  `protobuf:"varint,3,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyUnlockResponse) Reset() {
	*x = EmergencyUnlockResponse{}
	mi := &file_lockbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyUnlockResponse) ProtoMessage() {}

func (x *EmergencyUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyUnlockResponse.ProtoReflect.Descriptor instead.
func (*EmergencyUnlockResponse) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{12}
}

func (x *EmergencyUnlockResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *EmergencyUnlockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmergencyUnlockResponse) GetUnlockTime() int64 {
	if x != nil {
		return x.UnlockTime
	}
	return 0
}

type GetServiceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoRequest) Reset() {
	*x = GetServiceInfoRequest{}
	mi := &file_lockbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoRequest) ProtoMessage() {}

func (x *GetServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{13}
}

type GetServiceInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Tier          string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	MaxLockTime   int64                  `protobuf:"varint,3,opt,name=max_lock_time,json=maxLockTime,proto3" json:"max_lock_time,omitempty"`
	Features      *ServiceFeatures       `protobuf:"bytes,4,opt,name=features,proto3" json:"features,omitempty"`
	NodeLocations []string               `protobuf:"bytes,5,rep,name=node_locations,json=nodeLocations,proto3" json:"node_locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoResponse) Reset() {
	*x = GetServiceInfoResponse{}
	mi := &file_lockbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoResponse) ProtoMessage() {}

func (x *GetServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{14}
}

func (x *GetServiceInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServiceInfoResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *GetServiceInfoResponse) GetMaxLockTime() int64 {
	if x != nil {
		return x.MaxLockTime
	}
	return 0
}

func (x *GetServiceInfoResponse) GetFeatures() *ServiceFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *GetServiceInfoResponse) GetNodeLocations() []string {
	if x != nil {
		return x.NodeLocations
	}
	return nil
}

type ServiceFeatures struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MultiSigSupport      bool                   `protobuf:"varint,1,opt,name=multi_sig_support,json=multiSigSupport,proto3" json:"multi_sig_support,omitempty"`
	EmergencyUnlock      bool                   `protobuf:"varint,2,opt,name=emergency_unlock,json=emergencyUnlock,proto3" json:"emergency_unlock,omitempty"`
	GeographicRedundancy int32                  `protobuf:"varint,3,opt,name=geographic_redundancy,json=geographicRedundancy,proto3" json:"geographic_redundancy,omitempty"`
	ScriptingEnabled     bool                   `protobuf:"varint,4,opt,name=scripting_enabled,json=scriptingEnabled,proto3" json:"scripting_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServiceFeatures) Reset() {
	*x = ServiceFeatures{}
	mi := &file_lockbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceFeatures) ProtoMessage() {}

func (x *ServiceFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_lockbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceFeatures.ProtoReflect.Descriptor instead.
func (*ServiceFeatures) Descriptor() ([]byte, []int) {
	return file_lockbox_proto_rawDescGZIP(), []int{15}
}

func (x *ServiceFeatures) GetMultiSigSupport() bool {
	if x != nil {
		return x.MultiSigSupport
	}
	return false
}

func (x *ServiceFeatures) GetEmergencyUnlock() bool {
	if x != nil {
		return x.EmergencyUnlock
	}
	return false
}

func (x *ServiceFeatures) GetGeographicRedundancy() int32 {
	if x != nil {
		return x.GeographicRedundancy
	}
	return 0
}

func (x *ServiceFeatures) GetScriptingEnabled() bool {
	if x != nil {
		return x.ScriptingEnabled
	}
	return false
}

var File_lockbox_proto protoreflect.FileDescriptor

const file_lockbox_proto_rawDesc = "" +
	"\n" +
	"\rlockbox.proto\x12\alockbox\"\x80\x02\n" +
	"\x10LockAssetRequest\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12\x1b\n" +
	"\toutput_id\x18\x02 \x01(\fR\boutputId\x122\n" +
	"\x15lock_duration_seconds\x18\x03 \x01(\x03R\x13lockDurationSeconds\x12\x1f\n" +
	"\vlock_script\x18\x04 \x01(\tR\n" +
	"lockScript\x12.\n" +
	"\x13multi_sig_addresses\x18\x05 \x03(\tR\x11multiSigAddresses\x12%\n" +
	"\x0emin_signatures\x18\x06 \x01(\x05R\rminSignatures\"\x84\x01\n" +
	"\x11LockAssetResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1b\n" +
	"\tlock_time\x18\x02 \x01(\x03R\blockTime\x12\x1f\n" +
	"\vunlock_time\x18\x03 \x01(\x03R\n" +
	"unlockTime\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xe4\x01\n" +
	"\x12UnlockAssetRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1e\n" +
	"\n" +
	"signatures\x18\x02 \x03(\fR\n" +
	"signatures\x12R\n" +
	"\runlock_params\x18\x03 \x03(\v2-.lockbox.UnlockAssetRequest.UnlockParamsEntryR\funlockParams\x1a?\n" +
	"\x11UnlockParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x13UnlockAssetResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1b\n" +
	"\toutput_id\x18\x02 \x01(\fR\boutputId\x12\x1f\n" +
	"\vunlock_time\x18\x03 \x01(\x03R\n" +
	"unlockTime\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"2\n" +
	"\x15GetAssetStatusRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"\xc6\x01\n" +
	"\x16GetAssetStatusResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tlock_time\x18\x03 \x01(\x03R\blockTime\x12\x1f\n" +
	"\vunlock_time\x18\x04 \x01(\x03R\n" +
	"unlockTime\x12#\n" +
	"\rowner_address\x18\x05 \x01(\tR\fownerAddress\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x04R\x06amount\"\x8c\x01\n" +
	"\x11ListAssetsRequest\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"h\n" +
	"\x12ListAssetsResponse\x12*\n" +
	"\x06assets\x18\x01 \x03(\v2\x12.lockbox.AssetInfoR\x06assets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x94\x01\n" +
	"\tAssetInfo\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tlock_time\x18\x03 \x01(\x03R\blockTime\x12\x1f\n" +
	"\vunlock_time\x18\x04 \x01(\x03R\n" +
	"unlockTime\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x04R\x06amount\"\\\n" +
	"\x15CreateMultiSigRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12%\n" +
	"\x0emin_signatures\x18\x02 \x01(\x05R\rminSignatures\"T\n" +
	"\x16CreateMultiSigResponse\x12 \n" +
	"\fmulti_sig_id\x18\x01 \x01(\tR\n" +
	"multiSigId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"~\n" +
	"\x16EmergencyUnlockRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x121\n" +
	"\x14emergency_signatures\x18\x03 \x03(\fR\x13emergencySignatures\"m\n" +
	"\x17EmergencyUnlockResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vunlock_time\x18\x03 \x01(\x03R\n" +
	"unlockTime\"\x17\n" +
	"\x15GetServiceInfoRequest\"\xc7\x01\n" +
	"\x16GetServiceInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\"\n" +
	"\rmax_lock_time\x18\x03 \x01(\x03R\vmaxLockTime\x124\n" +
	"\bfeatures\x18\x04 \x01(\v2\x18.lockbox.ServiceFeaturesR\bfeatures\x12%\n" +
	"\x0enode_locations\x18\x05 \x03(\tR\rnodeLocations\"\xca\x01\n" +
	"\x0fServiceFeatures\x12*\n" +
	"\x11multi_sig_support\x18\x01 \x01(\bR\x0fmultiSigSupport\x12)\n" +
	"\x10emergency_unlock\x18\x02 \x01(\bR\x0femergencyUnlock\x123\n" +
	"\x15geographic_redundancy\x18\x03 \x01(\x05R\x14geographicRedundancy\x12+\n" +
	"\x11scripting_enabled\x18\x04 \x01(\bR\x10scriptingEnabled2\xb6\x04\n" +
	"\x0eLockBoxService\x12B\n" +
	"\tLockAsset\x12\x19.lockbox.LockAssetRequest\x1a\x1a.lockbox.LockAssetResponse\x12H\n" +
	"\vUnlockAsset\x12\x1b.lockbox.UnlockAssetRequest\x1a\x1c.lockbox.UnlockAssetResponse\x12Q\n" +
	"\x0eGetAssetStatus\x12\x1e.lockbox.GetAssetStatusRequest\x1a\x1f.lockbox.GetAssetStatusResponse\x12G\n" +
	"\n" +
	"ListAssets\x12\x1a.lockbox.ListAssetsRequest\x1a\x1b.lockbox.ListAssetsResponse0\x01\x12Q\n" +
	"\x0eCreateMultiSig\x12\x1e.lockbox.CreateMultiSigRequest\x1a\x1f.lockbox.CreateMultiSigResponse\x12T\n" +
	"\x0fEmergencyUnlock\x12\x1f.lockbox.EmergencyUnlockRequest\x1a .lockbox.EmergencyUnlockResponse\x12Q\n" +
	"\x0eGetServiceInfo\x12\x1e.lockbox.GetServiceInfoRequest\x1a\x1f.lockbox.GetServiceInfoResponseB0Z.github.com/dueldanov/lockbox/v2/internal/protob\x06proto3"

var (
	file_lockbox_proto_rawDescOnce sync.Once
	file_lockbox_proto_rawDescData []byte
)

func file_lockbox_proto_rawDescGZIP() []byte {
	file_lockbox_proto_rawDescOnce.Do(func() {
		file_lockbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lockbox_proto_rawDesc), len(file_lockbox_proto_rawDesc)))
	})
	return file_lockbox_proto_rawDescData
}

var file_lockbox_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_lockbox_proto_goTypes = []any{
	(*LockAssetRequest)(nil),        // 0: lockbox.LockAssetRequest
	(*LockAssetResponse)(nil),       // 1: lockbox.LockAssetResponse
	(*UnlockAssetRequest)(nil),      // 2: lockbox.UnlockAssetRequest
	(*UnlockAssetResponse)(nil),     // 3: lockbox.UnlockAssetResponse
	(*GetAssetStatusRequest)(nil),   // 4: lockbox.GetAssetStatusRequest
	(*GetAssetStatusResponse)(nil),  // 5: lockbox.GetAssetStatusResponse
	(*ListAssetsRequest)(nil),       // 6: lockbox.ListAssetsRequest
	(*ListAssetsResponse)(nil),      // 7: lockbox.ListAssetsResponse
	(*AssetInfo)(nil),               // 8: lockbox.AssetInfo
	(*CreateMultiSigRequest)(nil),   // 9: lockbox.CreateMultiSigRequest
	(*CreateMultiSigResponse)(nil),  // 10: lockbox.CreateMultiSigResponse
	(*EmergencyUnlockRequest)(nil),  // 11: lockbox.EmergencyUnlockRequest
	(*EmergencyUnlockResponse)(nil), // 12: lockbox.EmergencyUnlockResponse
	(*GetServiceInfoRequest)(nil),   // 13: lockbox.GetServiceInfoRequest
	(*GetServiceInfoResponse)(nil),  // 14: lockbox.GetServiceInfoResponse
	(*ServiceFeatures)(nil),         // 15: lockbox.ServiceFeatures
	nil,                             // 16: lockbox.UnlockAssetRequest.UnlockParamsEntry
}
var file_lockbox_proto_depIdxs = []int32{
	16, // 0: lockbox.UnlockAssetRequest.unlock_params:type_name -> lockbox.UnlockAssetRequest.UnlockParamsEntry
	8,  // 1: lockbox.ListAssetsResponse.assets:type_name -> lockbox.AssetInfo
	15, // 2: lockbox.GetServiceInfoResponse.features:type_name -> lockbox.ServiceFeatures
	0,  // 3: lockbox.LockBoxService.LockAsset:input_type -> lockbox.LockAssetRequest
	2,  // 4: lockbox.LockBoxService.UnlockAsset:input_type -> lockbox.UnlockAssetRequest
	4,  // 5: lockbox.LockBoxService.GetAssetStatus:input_type -> lockbox.GetAssetStatusRequest
	6,  // 6: lockbox.LockBoxService.ListAssets:input_type -> lockbox.ListAssetsRequest
	9,  // 7: lockbox.LockBoxService.CreateMultiSig:input_type -> lockbox.CreateMultiSigRequest
	11, // 8: lockbox.LockBoxService.EmergencyUnlock:input_type -> lockbox.EmergencyUnlockRequest
	13, // 9: lockbox.LockBoxService.GetServiceInfo:input_type -> lockbox.GetServiceInfoRequest
	1,  // 10: lockbox.LockBoxService.LockAsset:output_type -> lockbox.LockAssetResponse
	3,  // 11: lockbox.LockBoxService.UnlockAsset:output_type -> lockbox.UnlockAssetResponse
	5,  // 12: lockbox.LockBoxService.GetAssetStatus:output_type -> lockbox.GetAssetStatusResponse
	7,  // 13: lockbox.LockBoxService.ListAssets:output_type -> lockbox.ListAssetsResponse
	10, // 14: lockbox.LockBoxService.CreateMultiSig:output_type -> lockbox.CreateMultiSigResponse
	12, // 15: lockbox.LockBoxService.EmergencyUnlock:output_type -> lockbox.EmergencyUnlockResponse
	14, // 16: lockbox.LockBoxService.GetServiceInfo:output_type -> lockbox.GetServiceInfoResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_lockbox_proto_init() }
func file_lockbox_proto_init() {
	if File_lockbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lockbox_proto_rawDesc), len(file_lockbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lockbox_proto_goTypes,
		DependencyIndexes: file_lockbox_proto_depIdxs,
		MessageInfos:      file_lockbox_proto_msgTypes,
	}.Build()
	File_lockbox_proto = out.File
	file_lockbox_proto_goTypes = nil
	file_lockbox_proto_depIdxs = nil
}
