version: 2

run:
  timeout: 10m
  tests: true
  build-tags:
    - rocksdb

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: false
  misspell:
    locale: US
  staticcheck:
    checks: ["all"]
  nlreturn:
    block-size: 3
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

linters:
  disable-all: true
  enable:
    # Core linters (enabled by default in golangci-lint v2.x)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters compatible with v2.8.0
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - copyloopvar
    - forcetypeassert
    - goconst
    #- godot  # Disabled: comment formatting is not critical
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gosec
