// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: b2b_api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LockBoxAPI_CompileScript_FullMethodName        = "/lockbox.b2b.api.LockBoxAPI/CompileScript"
	LockBoxAPI_ExecuteScript_FullMethodName        = "/lockbox.b2b.api.LockBoxAPI/ExecuteScript"
	LockBoxAPI_ValidateScript_FullMethodName       = "/lockbox.b2b.api.LockBoxAPI/ValidateScript"
	LockBoxAPI_CreateVault_FullMethodName          = "/lockbox.b2b.api.LockBoxAPI/CreateVault"
	LockBoxAPI_GenerateKey_FullMethodName          = "/lockbox.b2b.api.LockBoxAPI/GenerateKey"
	LockBoxAPI_RotateKeys_FullMethodName           = "/lockbox.b2b.api.LockBoxAPI/RotateKeys"
	LockBoxAPI_GetVaultInfo_FullMethodName         = "/lockbox.b2b.api.LockBoxAPI/GetVaultInfo"
	LockBoxAPI_GetAccountInfo_FullMethodName       = "/lockbox.b2b.api.LockBoxAPI/GetAccountInfo"
	LockBoxAPI_UpgradeTier_FullMethodName          = "/lockbox.b2b.api.LockBoxAPI/UpgradeTier"
	LockBoxAPI_GetUsageStats_FullMethodName        = "/lockbox.b2b.api.LockBoxAPI/GetUsageStats"
	LockBoxAPI_SubmitTransaction_FullMethodName    = "/lockbox.b2b.api.LockBoxAPI/SubmitTransaction"
	LockBoxAPI_GetTransactionStatus_FullMethodName = "/lockbox.b2b.api.LockBoxAPI/GetTransactionStatus"
	LockBoxAPI_StreamTransactions_FullMethodName   = "/lockbox.b2b.api.LockBoxAPI/StreamTransactions"
	LockBoxAPI_StreamEvents_FullMethodName         = "/lockbox.b2b.api.LockBoxAPI/StreamEvents"
	LockBoxAPI_StoreKey_FullMethodName             = "/lockbox.b2b.api.LockBoxAPI/StoreKey"
	LockBoxAPI_RetrieveKey_FullMethodName          = "/lockbox.b2b.api.LockBoxAPI/RetrieveKey"
	LockBoxAPI_GetRevenueShare_FullMethodName      = "/lockbox.b2b.api.LockBoxAPI/GetRevenueShare"
	LockBoxAPI_GetPartnerStats_FullMethodName      = "/lockbox.b2b.api.LockBoxAPI/GetPartnerStats"
)

// LockBoxAPIClient is the client API for LockBoxAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LockBoxAPIClient interface {
	// LockScript operations
	CompileScript(ctx context.Context, in *CompileScriptRequest, opts ...grpc.CallOption) (*CompileScriptResponse, error)
	ExecuteScript(ctx context.Context, in *ExecuteScriptRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error)
	ValidateScript(ctx context.Context, in *ValidateScriptRequest, opts ...grpc.CallOption) (*ValidateScriptResponse, error)
	// Vault operations
	CreateVault(ctx context.Context, in *CreateVaultRequest, opts ...grpc.CallOption) (*CreateVaultResponse, error)
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error)
	RotateKeys(ctx context.Context, in *RotateKeysRequest, opts ...grpc.CallOption) (*RotateKeysResponse, error)
	GetVaultInfo(ctx context.Context, in *GetVaultInfoRequest, opts ...grpc.CallOption) (*VaultInfo, error)
	// Account operations
	GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*AccountInfo, error)
	UpgradeTier(ctx context.Context, in *UpgradeTierRequest, opts ...grpc.CallOption) (*UpgradeTierResponse, error)
	GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*UsageStats, error)
	// Transaction operations
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error)
	GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*TransactionStatus, error)
	// Streaming operations
	StreamTransactions(ctx context.Context, in *StreamTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Transaction], error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// B2B Key Storage API - Core endpoints for partner integrations
	StoreKey(ctx context.Context, in *StoreKeyRequest, opts ...grpc.CallOption) (*StoreKeyResponse, error)
	RetrieveKey(ctx context.Context, in *RetrieveKeyRequest, opts ...grpc.CallOption) (*RetrieveKeyResponse, error)
	GetRevenueShare(ctx context.Context, in *GetRevenueShareRequest, opts ...grpc.CallOption) (*GetRevenueShareResponse, error)
	GetPartnerStats(ctx context.Context, in *GetPartnerStatsRequest, opts ...grpc.CallOption) (*GetPartnerStatsResponse, error)
}

type lockBoxAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewLockBoxAPIClient(cc grpc.ClientConnInterface) LockBoxAPIClient {
	return &lockBoxAPIClient{cc}
}

func (c *lockBoxAPIClient) CompileScript(ctx context.Context, in *CompileScriptRequest, opts ...grpc.CallOption) (*CompileScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileScriptResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_CompileScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) ExecuteScript(ctx context.Context, in *ExecuteScriptRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteScriptResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_ExecuteScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) ValidateScript(ctx context.Context, in *ValidateScriptRequest, opts ...grpc.CallOption) (*ValidateScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateScriptResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_ValidateScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) CreateVault(ctx context.Context, in *CreateVaultRequest, opts ...grpc.CallOption) (*CreateVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVaultResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_CreateVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateKeyResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_GenerateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) RotateKeys(ctx context.Context, in *RotateKeysRequest, opts ...grpc.CallOption) (*RotateKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateKeysResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_RotateKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) GetVaultInfo(ctx context.Context, in *GetVaultInfoRequest, opts ...grpc.CallOption) (*VaultInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultInfo)
	err := c.cc.Invoke(ctx, LockBoxAPI_GetVaultInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*AccountInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountInfo)
	err := c.cc.Invoke(ctx, LockBoxAPI_GetAccountInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) UpgradeTier(ctx context.Context, in *UpgradeTierRequest, opts ...grpc.CallOption) (*UpgradeTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeTierResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_UpgradeTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*UsageStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageStats)
	err := c.cc.Invoke(ctx, LockBoxAPI_GetUsageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTransactionResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*TransactionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionStatus)
	err := c.cc.Invoke(ctx, LockBoxAPI_GetTransactionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) StreamTransactions(ctx context.Context, in *StreamTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Transaction], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LockBoxAPI_ServiceDesc.Streams[0], LockBoxAPI_StreamTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTransactionsRequest, Transaction]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LockBoxAPI_StreamTransactionsClient = grpc.ServerStreamingClient[Transaction]

func (c *lockBoxAPIClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LockBoxAPI_ServiceDesc.Streams[1], LockBoxAPI_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LockBoxAPI_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *lockBoxAPIClient) StoreKey(ctx context.Context, in *StoreKeyRequest, opts ...grpc.CallOption) (*StoreKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreKeyResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_StoreKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) RetrieveKey(ctx context.Context, in *RetrieveKeyRequest, opts ...grpc.CallOption) (*RetrieveKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveKeyResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_RetrieveKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) GetRevenueShare(ctx context.Context, in *GetRevenueShareRequest, opts ...grpc.CallOption) (*GetRevenueShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevenueShareResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_GetRevenueShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockBoxAPIClient) GetPartnerStats(ctx context.Context, in *GetPartnerStatsRequest, opts ...grpc.CallOption) (*GetPartnerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartnerStatsResponse)
	err := c.cc.Invoke(ctx, LockBoxAPI_GetPartnerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockBoxAPIServer is the server API for LockBoxAPI service.
// All implementations must embed UnimplementedLockBoxAPIServer
// for forward compatibility.
type LockBoxAPIServer interface {
	// LockScript operations
	CompileScript(context.Context, *CompileScriptRequest) (*CompileScriptResponse, error)
	ExecuteScript(context.Context, *ExecuteScriptRequest) (*ExecuteScriptResponse, error)
	ValidateScript(context.Context, *ValidateScriptRequest) (*ValidateScriptResponse, error)
	// Vault operations
	CreateVault(context.Context, *CreateVaultRequest) (*CreateVaultResponse, error)
	GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error)
	RotateKeys(context.Context, *RotateKeysRequest) (*RotateKeysResponse, error)
	GetVaultInfo(context.Context, *GetVaultInfoRequest) (*VaultInfo, error)
	// Account operations
	GetAccountInfo(context.Context, *GetAccountInfoRequest) (*AccountInfo, error)
	UpgradeTier(context.Context, *UpgradeTierRequest) (*UpgradeTierResponse, error)
	GetUsageStats(context.Context, *GetUsageStatsRequest) (*UsageStats, error)
	// Transaction operations
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error)
	GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*TransactionStatus, error)
	// Streaming operations
	StreamTransactions(*StreamTransactionsRequest, grpc.ServerStreamingServer[Transaction]) error
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	// B2B Key Storage API - Core endpoints for partner integrations
	StoreKey(context.Context, *StoreKeyRequest) (*StoreKeyResponse, error)
	RetrieveKey(context.Context, *RetrieveKeyRequest) (*RetrieveKeyResponse, error)
	GetRevenueShare(context.Context, *GetRevenueShareRequest) (*GetRevenueShareResponse, error)
	GetPartnerStats(context.Context, *GetPartnerStatsRequest) (*GetPartnerStatsResponse, error)
	mustEmbedUnimplementedLockBoxAPIServer()
}

// UnimplementedLockBoxAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLockBoxAPIServer struct{}

func (UnimplementedLockBoxAPIServer) CompileScript(context.Context, *CompileScriptRequest) (*CompileScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompileScript not implemented")
}
func (UnimplementedLockBoxAPIServer) ExecuteScript(context.Context, *ExecuteScriptRequest) (*ExecuteScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteScript not implemented")
}
func (UnimplementedLockBoxAPIServer) ValidateScript(context.Context, *ValidateScriptRequest) (*ValidateScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateScript not implemented")
}
func (UnimplementedLockBoxAPIServer) CreateVault(context.Context, *CreateVaultRequest) (*CreateVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVault not implemented")
}
func (UnimplementedLockBoxAPIServer) GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateKey not implemented")
}
func (UnimplementedLockBoxAPIServer) RotateKeys(context.Context, *RotateKeysRequest) (*RotateKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateKeys not implemented")
}
func (UnimplementedLockBoxAPIServer) GetVaultInfo(context.Context, *GetVaultInfoRequest) (*VaultInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVaultInfo not implemented")
}
func (UnimplementedLockBoxAPIServer) GetAccountInfo(context.Context, *GetAccountInfoRequest) (*AccountInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountInfo not implemented")
}
func (UnimplementedLockBoxAPIServer) UpgradeTier(context.Context, *UpgradeTierRequest) (*UpgradeTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeTier not implemented")
}
func (UnimplementedLockBoxAPIServer) GetUsageStats(context.Context, *GetUsageStatsRequest) (*UsageStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsageStats not implemented")
}
func (UnimplementedLockBoxAPIServer) SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedLockBoxAPIServer) GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*TransactionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (UnimplementedLockBoxAPIServer) StreamTransactions(*StreamTransactionsRequest, grpc.ServerStreamingServer[Transaction]) error {
	return status.Error(codes.Unimplemented, "method StreamTransactions not implemented")
}
func (UnimplementedLockBoxAPIServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedLockBoxAPIServer) StoreKey(context.Context, *StoreKeyRequest) (*StoreKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreKey not implemented")
}
func (UnimplementedLockBoxAPIServer) RetrieveKey(context.Context, *RetrieveKeyRequest) (*RetrieveKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveKey not implemented")
}
func (UnimplementedLockBoxAPIServer) GetRevenueShare(context.Context, *GetRevenueShareRequest) (*GetRevenueShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevenueShare not implemented")
}
func (UnimplementedLockBoxAPIServer) GetPartnerStats(context.Context, *GetPartnerStatsRequest) (*GetPartnerStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartnerStats not implemented")
}
func (UnimplementedLockBoxAPIServer) mustEmbedUnimplementedLockBoxAPIServer() {}
func (UnimplementedLockBoxAPIServer) testEmbeddedByValue()                    {}

// UnsafeLockBoxAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LockBoxAPIServer will
// result in compilation errors.
type UnsafeLockBoxAPIServer interface {
	mustEmbedUnimplementedLockBoxAPIServer()
}

func RegisterLockBoxAPIServer(s grpc.ServiceRegistrar, srv LockBoxAPIServer) {
	// If the following call panics, it indicates UnimplementedLockBoxAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LockBoxAPI_ServiceDesc, srv)
}

func _LockBoxAPI_CompileScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).CompileScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_CompileScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).CompileScript(ctx, req.(*CompileScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_ExecuteScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).ExecuteScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_ExecuteScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).ExecuteScript(ctx, req.(*ExecuteScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_ValidateScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).ValidateScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_ValidateScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).ValidateScript(ctx, req.(*ValidateScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_CreateVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).CreateVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_CreateVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).CreateVault(ctx, req.(*CreateVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_GenerateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_RotateKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).RotateKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_RotateKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).RotateKeys(ctx, req.(*RotateKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_GetVaultInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVaultInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).GetVaultInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_GetVaultInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).GetVaultInfo(ctx, req.(*GetVaultInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_GetAccountInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).GetAccountInfo(ctx, req.(*GetAccountInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_UpgradeTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).UpgradeTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_UpgradeTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).UpgradeTier(ctx, req.(*UpgradeTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_GetUsageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).GetUsageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_GetUsageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).GetUsageStats(ctx, req.(*GetUsageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_GetTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).GetTransactionStatus(ctx, req.(*GetTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_StreamTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LockBoxAPIServer).StreamTransactions(m, &grpc.GenericServerStream[StreamTransactionsRequest, Transaction]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LockBoxAPI_StreamTransactionsServer = grpc.ServerStreamingServer[Transaction]

func _LockBoxAPI_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LockBoxAPIServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LockBoxAPI_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _LockBoxAPI_StoreKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).StoreKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_StoreKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).StoreKey(ctx, req.(*StoreKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_RetrieveKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).RetrieveKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_RetrieveKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).RetrieveKey(ctx, req.(*RetrieveKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_GetRevenueShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevenueShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).GetRevenueShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_GetRevenueShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).GetRevenueShare(ctx, req.(*GetRevenueShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockBoxAPI_GetPartnerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartnerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockBoxAPIServer).GetPartnerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockBoxAPI_GetPartnerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockBoxAPIServer).GetPartnerStats(ctx, req.(*GetPartnerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LockBoxAPI_ServiceDesc is the grpc.ServiceDesc for LockBoxAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LockBoxAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lockbox.b2b.api.LockBoxAPI",
	HandlerType: (*LockBoxAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompileScript",
			Handler:    _LockBoxAPI_CompileScript_Handler,
		},
		{
			MethodName: "ExecuteScript",
			Handler:    _LockBoxAPI_ExecuteScript_Handler,
		},
		{
			MethodName: "ValidateScript",
			Handler:    _LockBoxAPI_ValidateScript_Handler,
		},
		{
			MethodName: "CreateVault",
			Handler:    _LockBoxAPI_CreateVault_Handler,
		},
		{
			MethodName: "GenerateKey",
			Handler:    _LockBoxAPI_GenerateKey_Handler,
		},
		{
			MethodName: "RotateKeys",
			Handler:    _LockBoxAPI_RotateKeys_Handler,
		},
		{
			MethodName: "GetVaultInfo",
			Handler:    _LockBoxAPI_GetVaultInfo_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _LockBoxAPI_GetAccountInfo_Handler,
		},
		{
			MethodName: "UpgradeTier",
			Handler:    _LockBoxAPI_UpgradeTier_Handler,
		},
		{
			MethodName: "GetUsageStats",
			Handler:    _LockBoxAPI_GetUsageStats_Handler,
		},
		{
			MethodName: "SubmitTransaction",
			Handler:    _LockBoxAPI_SubmitTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _LockBoxAPI_GetTransactionStatus_Handler,
		},
		{
			MethodName: "StoreKey",
			Handler:    _LockBoxAPI_StoreKey_Handler,
		},
		{
			MethodName: "RetrieveKey",
			Handler:    _LockBoxAPI_RetrieveKey_Handler,
		},
		{
			MethodName: "GetRevenueShare",
			Handler:    _LockBoxAPI_GetRevenueShare_Handler,
		},
		{
			MethodName: "GetPartnerStats",
			Handler:    _LockBoxAPI_GetPartnerStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTransactions",
			Handler:       _LockBoxAPI_StreamTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _LockBoxAPI_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "b2b_api.proto",
}
